// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package container

import (
	"go.mongodb.org/mongo-driver/mongo"
	"our-expenses-server/config"
	"our-expenses-server/db"
	"our-expenses-server/db/repositories"
	"our-expenses-server/logger"
	"our-expenses-server/validators"
	"our-expenses-server/web/api"
	"our-expenses-server/web/api/controllers"
	"our-expenses-server/web/server"
)

// Injectors from container.go:

func CreateServer(database *mongo.Database) (*server.Server, error) {
	configConfig, err := config.ProvideConfiguration()
	if err != nil {
		return nil, err
	}
	appLogger, err := logger.ProvideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	categoryRepository := repositories.ProvideCategoryRepository(database)
	validator := validators.ProvideValidator()
	categoryController := controllers.ProvideCategoryController(categoryRepository, appLogger, validator)
	router := api.ProvideRouter(categoryController)
	serverServer, err := server.ProvideServer(configConfig, appLogger, router)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}

func InitDatabase() (*mongo.Database, error) {
	configConfig, err := config.ProvideConfiguration()
	if err != nil {
		return nil, err
	}
	appLogger, err := logger.ProvideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	database, err := db.CreateMongoDBPool(configConfig, appLogger)
	if err != nil {
		return nil, err
	}
	return database, nil
}
