run:
  timeout: 10m
  tests: true

output:
  sort-results: true

linters-settings:
  govet:
    check-shadowing: true
  wrapcheck:
    ignoreSigs:
      - (github.com/labstack/echo/v4.Context).JSON(
      - (github.com/labstack/echo/v4.Context).NoContent(
      - errors.Wrap(
      - errors.Wrapf(
      - errors.New(
      - fmt.Errorf(

issues:
  exclude-use-default: false
  include:
    - EXC0002 # golint (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    - EXC0003 # golint func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
    - EXC0004 # govet (possible misuse of unsafe.Pointer|should have signature)
    - EXC0005 # staticcheck ineffective break statement. Did you mean to break out of the outer loop
    - EXC0011 # stylecheck (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)

  exclude-rules:
    - path: .*_test.go
      linters:
        - noctx
        - dupl
        - cyclop
        - errcheck
        - gosec
        - lll
        - funlen
        - gocognit
        - goconst
        - goerr113
        - wrapcheck
  max-same-issues: 0
  new: false
  max-issues-per-linter: 0

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    # - exhaustivestruct # don't want to initialize all struct fields
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    # - gci # want to have spaces between go imports
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    # - goerr113 # sometimes don't want to use static errors
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - ifshort
    - importas
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    # - nilnil # want to return nil,nil
    # - nlreturn # sometimes don't want to have a blank line before return
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    # - stylecheck # don't want to have package comments
    - tagliatelle
    - tenv
    # - testpackage # don't want to use separate _test packages
    - thelper
    - tparallel
    - unconvert
    - unparam
    # - varnamelen # want to have short enough variables
    - wastedassign
    - whitespace
    - wrapcheck
    # - wsl # annoying cuddle declarations
