// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package ports

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xUPW/bQAz9KwLbUY3cZNPWJinQIkCGpOgQZLhItHWpdHcleakNw/+94EmKXVvuB5Ch",
	"QxdDEp8fycdHrqHyXfAOnTCUa+Cqwc6kx3dRGnRiKyPWuwsjRr8G8gFJLCaMrfVXVgGhBBaybgGbHAjn",
	"hNzc+q/oJgFyNBIZyZkOJ4KJ+Fu0hDWUd5p7Bz5y7iW/z0cW//CIlWiKSyJPh71Uvk5Za+SKbNCmoezB",
	"WYrlMPfUGYESrJOzU3jmtk5wgaTkHTKbxVGiMZz/prkh4QifauMzI50T1joj0/JhQ8Ewf/eURtSZ5RW6",
	"hTRQns5y6KwbX8/yXw/hb/6518TOcJ5rOexkkwNjFcnK6kbd1xf/gIaQ1IPbtw+j/J++3ELee1WZ+uhW",
	"00YkwEaJrZv7w1HcXl9cK9pKq/DrSNnlMqBj5IyRnhLXExL38Lcns5OZyuIDOhMslHCWPmlb0qRyi9Yv",
	"bHJ08CyHKXeWCTlTYTLrMmkw4xULdieQ6Cnt2scaSrhKhL2gyPLe16vepU7QpQwmhHbYzuKRvdvurz69",
	"JpxDCa+K7YIXw3YX+9ZJWv1csEKyagezO1qhiGnWHLyqpvlOZ7MXq2/i9EyUmBTKxiIgxecmtvJidfSX",
	"YiJ1dLgMWAnWGQ6YHDh2naHV3rTTsFO8YLtwMRw3yTlhsofa4k8sctPz/ffIcY+oRG9i+CddMtY2GCTd",
	"QT0+DOXdGiK1wynjsijWjWfRW7op9ALl8GTImoe213UM9pYauoPWV6bVkJLfb34EAAD//5+C9OPrBwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
