// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package ports

// AuthenticationData defines model for AuthenticationData.
type AuthenticationData struct {
	Id           string `json:"id"`
	RefreshToken string `json:"refreshToken"`
	Token        string `json:"token"`
	Username     string `json:"username"`
}

// Error defines model for Error.
type Error struct {
	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// UserCredentials defines model for UserCredentials.
type UserCredentials struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody UserCredentials

// SignupJSONBody defines parameters for Signup.
type SignupJSONBody UserCredentials

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody SignupJSONBody
