openapi: "3.0.0"
info:
  version: 1.0.0
  title: Our Expenses server
  description: TODO
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
security:
  # - bearerAuth: []
paths:
  /expenses:
    post:
      summary: Creates a new expense
      description: Creates a new expense in the system.
      operationId: addExpense
      requestBody:
        description: Expense to add to the system
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewExpense"
      responses:
        "200":
          description: Expense response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewExpenseResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /reports:
    get:
      summary: Generates expense repose
      description: Generates expense report.
      operationId: generateReport
      parameters:
        - name: from
          in: query
          description: from date to filter by
          required: true
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: to date to filter by
          required: true
          schema:
            type: string
            format: date-time
        - name: interval
          in: query
          description: results interval
          required: true
          schema:
            $ref: "#/components/schemas/Interval"
      responses:
        "200":
          description: Expense report response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpenseReport"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Interval:
      type: string
      enum:
        - day
        - month
        - year
    Expense:
      allOf:
        - $ref: "#/components/schemas/NewExpense"
        - required:
            - id
          properties:
            id:
              type: string
              format: uuid
              description: Unique id of the expense
            category:
              $ref: "#/components/schemas/Category"
    NewExpense:
      type: object
      required:
        - categoryId
        - price
        - quantity
        - currency
        - date
        - totalInfo
      properties:
        categoryId:
          type: string
          format: uuid
          description: Category ID of the expense
        price:
          type: number
          format: double
        quantity:
          type: number
          format: double
        currency:
          type: string
        comment:
          type: string
        trip:
          type: string
        date:
          type: string
          format: date-time
        totalInfo:
          $ref: "#/components/schemas/TotalInfo"
    NewExpenseResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
          description: ID of the newly added expense
    ExpenseReport:
      type: object
      required:
        - dateReports
        - grandTotal
      properties:
        dateReports:
          type: array
          items:
            $ref: "#/components/schemas/DateCategoryReport"
        grandTotal:
          $ref: "#/components/schemas/GrandTotal"
    DateCategoryReport:
      type: object
      required:
        - date
        - categoryExpenses
        - grandTotal
        - exchangeRates
      properties:
        date:
          type: string
          format: date-time
        categoryExpenses:
          type: array
          items:
            $ref: "#/components/schemas/CategoryExpenses"
        grandTotal:
          $ref: "#/components/schemas/GrandTotal"
        exchangeRates:
          $ref: "#/components/schemas/ExchangeRates"
    CategoryExpenses:
      type: object
      required:
        - category
        - grandTotal
      properties:
        category:
          $ref: "#/components/schemas/Category"
        expenses:
          type: array
          items:
            $ref: "#/components/schemas/Expense"
        subCategories:
          type: array
          items:
            $ref: "#/components/schemas/CategoryExpenses"
        grandTotal:
          $ref: "#/components/schemas/GrandTotal"
    Category:
      type: object
      required:
        - id
        - name
        - path
        - level
      properties:
        id:
          type: string
          format: uuid
          description: Unique id of the category
        name:
          type: string
          description: Name of the category
        icon:
          type: string
        level:
          type: integer
        parents:
          type: array
          items:
            $ref: "#/components/schemas/Category"
    Total:
      type: object
      required:
        - sum
        - currency
      properties:
        sum:
          type: string
          description: Total sum amount
        currency:
          type: string
          description: Total currency
    TotalInfo:
      type: object
      required:
        - original
      properties:
        original:
          type: object
          $ref: "#/components/schemas/Total"
        rate:
          type: object
          $ref: "#/components/schemas/ExchangeRate"
        converted:
          type: object
          $ref: "#/components/schemas/Total"
    GrandTotal:
      type: object
      required:
        - subTotals
        - total
      properties:
        subTotals:
          type: array
          items:
            $ref: "#/components/schemas/TotalInfo"
        total:
          type: object
          $ref: "#/components/schemas/Total"
    ExchangeRate:
      type: object
      required:
        - date
        - baseCurrency
        - targetCurrency
        - rate
      properties:
        rate:
          type: string
        baseCurrency:
          type: string
        targetCurrency:
          type: string
        date:
          type: string
          format: date-time
    ExchangeRates:
      type: object
      required:
        - date
        - currency
        - rates
      properties:
        rates:
          type: array
          items:
            $ref: "#/components/schemas/Rate"
        currency:
          type: string
        date:
          type: string
          format: date-time
    Rate:
      type: object
      required:
        - currency
        - price
      properties:
        currency:
          type: string
        price:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
