server:
  name: our-expenses
  host: localhost
  port: 8080
  timeout:
    shutdown: 10
    read: 15
    write: 10
    idle: 5

logger:
  name: our-expenses
  level: DEBUG
  jsonFormat: false
  writers:
    file:
      enabled: true
      path: "storage/logs/app.log"

database:
  mongo:
    name: our-expenses
    uri: "#{mongo-uri}#"
    user: "#{mongo-user}#"
    pass: "#{mongo-pass}#"
    database: "#{mongo-db}#"

telemetry:
  name: our-expenses
  level: DEBUG
  token: "#{telemetry-token}#"
