// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package ports

// Category defines model for Category.
type Category struct {
	Id       string     `json:"id"`
	Level    int        `json:"level"`
	Name     string     `json:"name"`
	ParentId string     `json:"parentId"`
	Parents  []Category `json:"parents"`
	Path     string     `json:"path"`
}

// Error defines model for Error.
type Error struct {
	Error  string `json:"error"`
	Status string `json:"status"`
}
