// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	command "dev.azure.com/filimonovga/our-expenses/our-expenses-server/internal/categories/app/command"

	mock "github.com/stretchr/testify/mock"
)

// AddCategoryHandlerInterface is an autogenerated mock type for the AddCategoryHandlerInterface type
type AddCategoryHandlerInterface struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, category
func (_m *AddCategoryHandlerInterface) Handle(ctx context.Context, category command.NewCategory) (*string, error) {
	ret := _m.Called(ctx, category)

	var r0 *string
	if rf, ok := ret.Get(0).(func(context.Context, command.NewCategory) *string); ok {
		r0 = rf(ctx, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, command.NewCategory) error); ok {
		r1 = rf(ctx, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
