// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// CategoryControllerInterface is an autogenerated mock type for the CategoryControllerInterface type
type CategoryControllerInterface struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: w, req
func (_m *CategoryControllerInterface) CreateCategory(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// DeleteCategory provides a mock function with given fields: w, req
func (_m *CategoryControllerInterface) DeleteCategory(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// GetAllCategories provides a mock function with given fields: w, req
func (_m *CategoryControllerInterface) GetAllCategories(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// GetCategory provides a mock function with given fields: w, req
func (_m *CategoryControllerInterface) GetCategory(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// GetCategoryUsages provides a mock function with given fields: w, req
func (_m *CategoryControllerInterface) GetCategoryUsages(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// MoveCategory provides a mock function with given fields: w, req
func (_m *CategoryControllerInterface) MoveCategory(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// UpdateCategory provides a mock function with given fields: w, req
func (_m *CategoryControllerInterface) UpdateCategory(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}
