// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// CategoryControllerInterface is an autogenerated mock type for the CategoryControllerInterface type
type CategoryControllerInterface struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: w, req
func (_m *CategoryControllerInterface) CreateCategory(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// GetAllCategories provides a mock function with given fields: w, req
func (_m *CategoryControllerInterface) GetAllCategories(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}
