// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "dev.azure.com/filimonovga/our-expenses/our-expenses-server/internal/expenses/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ExchangeRateFetcherInterface is an autogenerated mock type for the ExchangeRateFetcherInterface type
type ExchangeRateFetcherInterface struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, dates
func (_m *ExchangeRateFetcherInterface) Fetch(ctx context.Context, dates []time.Time) ([]domain.ExchangeRates, error) {
	ret := _m.Called(ctx, dates)

	var r0 []domain.ExchangeRates
	if rf, ok := ret.Get(0).(func(context.Context, []time.Time) []domain.ExchangeRates); ok {
		r0 = rf(ctx, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ExchangeRates)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []time.Time) error); ok {
		r1 = rf(ctx, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
