// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "dev.azure.com/filimonovga/our-expenses/our-expenses-server/internal/expenses/domain"
	mock "github.com/stretchr/testify/mock"
)

// ReportRepoInterface is an autogenerated mock type for the ReportRepoInterface type
type ReportRepoInterface struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx, filter
func (_m *ReportRepoInterface) GetAll(ctx context.Context, filter domain.ExpenseFilter) ([]domain.Expense, error) {
	ret := _m.Called(ctx, filter)

	var r0 []domain.Expense
	if rf, ok := ret.Get(0).(func(context.Context, domain.ExpenseFilter) []domain.Expense); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Expense)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.ExpenseFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
