// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TraceInterface is an autogenerated mock type for the TraceInterface type
type TraceInterface struct {
	mock.Mock
}

// Shutdown provides a mock function with given fields:
func (_m *TraceInterface) Shutdown() {
	_m.Called()
}
