// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	command "dev.azure.com/filimonovga/our-expenses/our-expenses-server/internal/categories/app/command"

	mock "github.com/stretchr/testify/mock"
)

// UpdateCategoryHandlerInterface is an autogenerated mock type for the UpdateCategoryHandlerInterface type
type UpdateCategoryHandlerInterface struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, category
func (_m *UpdateCategoryHandlerInterface) Handle(ctx context.Context, category command.UpdateCategoryCommandArgs) error {
	ret := _m.Called(ctx, category)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.UpdateCategoryCommandArgs) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
