// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	command "dev.azure.com/filimonovga/our-expenses/our-expenses-server/internal/categories/app/command"

	domain "dev.azure.com/filimonovga/our-expenses/our-expenses-server/internal/categories/domain"

	mock "github.com/stretchr/testify/mock"
)

// UpdateCategoryHandlerInterface is an autogenerated mock type for the UpdateCategoryHandlerInterface type
type UpdateCategoryHandlerInterface struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, args
func (_m *UpdateCategoryHandlerInterface) Handle(ctx context.Context, args command.UpdateCategoryCommandArgs) (*domain.UpdateResult, error) {
	ret := _m.Called(ctx, args)

	var r0 *domain.UpdateResult
	if rf, ok := ret.Get(0).(func(context.Context, command.UpdateCategoryCommandArgs) *domain.UpdateResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UpdateResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, command.UpdateCategoryCommandArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
