// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import validators "our-expenses-server/validators"

// ValidatorInterface is an autogenerated mock type for the ValidatorInterface type
type ValidatorInterface struct {
	mock.Mock
}

// ValidateStruct provides a mock function with given fields: object
func (_m *ValidatorInterface) ValidateStruct(object interface{}) []validators.ValidationError {
	ret := _m.Called(object)

	var r0 []validators.ValidationError
	if rf, ok := ret.Get(0).(func(interface{}) []validators.ValidationError); ok {
		r0 = rf(object)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]validators.ValidationError)
		}
	}

	return r0
}
